SmsScheduler/SmsWeb/Controllers/SmsAndEmailController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using CsvHelper.Configuration;
using NServiceBus;
using SmsMessages.CommonData;
using SmsTrackingModels;
using SmsTrackingModels.RavenIndexs;
using SmsWeb.Models;

namespace SmsWeb.Controllers
{
    public class SmsAndEmailController : Controller
    {
        public IBus Bus { get; set; }
        public IRavenDocStore Raven { get; set; }
        public ICoordinatorModelToMessageMapping Mapper { get; set; }
        public ICurrentUser CurrentUser { get; set; }

        public ActionResult Create()
        {

            List<SelectListItem> templateItems;
            using (var session = Raven.GetStore().OpenSession("Configuration"))
            {
                templateItems.add(new SelectListItem { Selected = true, Text = string.Empty, Value = string.Empty});
                var templates = session.Query<CommunicationTemplate>().Take(30).ToList();
                templateItems = templates.Select(c => new SelectListItem { Selected = false, Text = c.TemplateName, Value = c.TemplateName }).ToList();
            }
            ViewData.Add("CommunicationTemplates", templateItems);

            return View("CreateSmsAndEmail");
        }

        [HttpPost]
        public ActionResult Create(CoordinatorSmsAndEmailModel model)
        {
            var trickleId = Guid.NewGuid();
            Session.Add("CoordinatorSmsAndEmailModel", model);
            Session.Add("trickleId", trickleId.ToString());
            var hpf = Request.Files[0];
            if (hpf.ContentLength == 0)
                throw new ArgumentException("no content");

            var csvFileContents = new CsvFileContents();
            using (var csvReader = new CsvHelper.CsvReader(new StreamReader(hpf.InputStream), new CsvConfiguration { HasHeaderRecord = false }))
            {
                // TODO : Not reading first row properly
                while (csvReader.Read())
                {
                    csvFileContents.Rows.Add(csvReader.CurrentRecord);
                }
            }
            
            var fileContentsId = trickleId.ToString() + "_fileContents";
            using (var session = Raven.GetStore().OpenSession())
            {
                session.Store(csvFileContents, fileContentsId);
                session.SaveChanges();
            }

            var dataColumnPicker = new DataColumnPicker {TrickleId = trickleId, FirstRowIsHeader = true};

            var dropDownList = csvFileContents.CreateSelectList();
            ViewData.Add("selectListData", dropDownList);
            return View("CreateSmsAndEmailPickRows", dataColumnPicker);
        }

        [HttpPost]
        public ActionResult CreateSmsAndEmailColumnPicker(DataColumnPicker model)
        {
            var trickleIdString = Session["trickleId"] as string;
            // TODO: Validate column to data mapping

            var originalRequest = Session["CoordinatorSmsAndEmailModel"] as CoordinatorSmsAndEmailModel;

            var fileContentsId = trickleIdString + "_fileContents";
            CsvFileContents fileContents;
            using (var session = Raven.GetStore().OpenSession())
            {
                fileContents = session.Load<CsvFileContents>(fileContentsId);
            }

            var customerContacts = new List<CustomerContact>();

            for (int i = 0; i < fileContents.Rows.Count; i++)
            {
                if (i > 0 || !model.FirstRowIsHeader)
                {
                    var customerContact = new CustomerContact();
                    if (model.PhoneNumberColumn.HasValue)
                        customerContact.MobileNumber = fileContents.Rows[i][model.PhoneNumberColumn.Value];
                    if (model.EmailColumn.HasValue)
                        customerContact.EmailAddress = fileContents.Rows[i][model.EmailColumn.Value];
                    if (model.CustomerNameColumn.HasValue)
                        customerContact.CustomerName = fileContents.Rows[i][model.CustomerNameColumn.Value];
                    customerContacts.Add(customerContact);
                }
            }

            using (var transaction = new TransactionScope())
            {
                var customerContactsId = trickleIdString + "_customerContacts";
                using (var session = Raven.GetStore().OpenSession())
                {
                    session.Store(new CustomerContactList(customerContacts), customerContactsId);
                    session.SaveChanges();
                }
                var message = Mapper.MapToTrickleSmsAndEmailOverPeriod(Guid.Parse(trickleIdString), customerContactsId, originalRequest, CurrentUser.Name());
                Bus.Send("smscoordinator", message);
                transaction.Complete();
            }
            //return View("CreateSmsAndEmail");
            return RedirectToAction("Details", new { coordinatorId = trickleIdString });
        }

        public ActionResult Details(string coordinatorId)
        {
            using (var session = Raven.GetStore().OpenSession())
            {
                var coordinatorSummary = session.Query<ScheduledMessagesStatusCountInCoordinatorIndex.ReduceResult, ScheduledMessagesStatusCountInCoordinatorIndex>()
                    .Where(s => s.CoordinatorId == coordinatorId)
                    .ToList();
                var coordinatorTrackingData = session.Load<CoordinatorTrackingData>(coordinatorId);
                if (coordinatorSummary.Count == 0 || coordinatorTrackingData == null)
                {
                    throw new NotImplementedException("need to have some data...");
                    return View("DetailsNotCreated", model: coordinatorId);
                }

                DateTime? nextSmsDateUtc = session.Query<ScheduleTrackingData, ScheduleMessagesInCoordinatorIndex>()
                                 .Where(s => s.CoordinatorId == Guid.Parse(coordinatorId) && s.MessageStatus == MessageStatus.Scheduled)
                                 .OrderBy(s => s.ScheduleTimeUtc)
                                 .Select(s => s.ScheduleTimeUtc)
                                 .FirstOrDefault();
                if (nextSmsDateUtc == DateTime.MinValue)
                    nextSmsDateUtc = null;

                DateTime? finalSmsDateUtc = session.Query<ScheduleTrackingData, ScheduleMessagesInCoordinatorIndex>()
                    .Where(s => s.CoordinatorId == Guid.Parse(coordinatorId) && s.MessageStatus == MessageStatus.Scheduled)
                    .OrderByDescending(s => s.ScheduleTimeUtc)
                    .Select(s => s.ScheduleTimeUtc)
                    .FirstOrDefault();
                if (finalSmsDateUtc == DateTime.MinValue)
                    finalSmsDateUtc = null;

                var overview = new CoordinatorOverview(coordinatorTrackingData, coordinatorSummary);
                overview.NextScheduledMessageDate = nextSmsDateUtc;
                overview.FinalScheduledMessageDate = finalSmsDateUtc;
                if (HttpContext.Session != null && HttpContext.Session["CoordinatorState_" + coordinatorId] != null && HttpContext.Session["CoordinatorState_" + coordinatorId] is CoordinatorStatusTracking)
                    overview.CurrentStatus = (CoordinatorStatusTracking)HttpContext.Session["CoordinatorState_" + coordinatorId];
                return View("Details", overview);
            }
        }
    }

    public class CsvFileContents
    {
        public CsvFileContents()
        {
            Rows = new List<string[]>();
        }
        public List<string[]> Rows { get; set; }

        public List<SelectListItem> CreateSelectList()
        {
            var selectListItems = new List<SelectListItem>();
            selectListItems.Add(new SelectListItem { Selected = true, Text = "Not In Data", Value = null});
            var rowDatas = Rows.Take(5).ToList();
            var columnCount = 0;
            if (rowDatas.Count > 0)
                columnCount = rowDatas[0].Count();

            for (int i = 0; i < columnCount; i++)
            {
                var columnValues = rowDatas.Select(r => r[i]).ToList();
                var text = "Column " + i.ToString() + ": " + string.Join(",", columnValues);
                selectListItems.Add(new SelectListItem { Selected = false, Text = text, Value = i.ToString() });
            }
            return selectListItems;
        }
    }
}

SmsScheduler/SmsWeb/Views/SmsAndEmail/CreateSmsAndEmail.cshtml
@model SmsWeb.Models.CoordinatorSmsAndEmailModel

@{
    ViewBag.Title = "SMS Create";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Styles.Render("~/Content/themes/base/jquery-ui.css")

<script type="text/javascript" src="~/Scripts/jquery-ui-timepicker-addon.js" ></script>
<script type="text/javascript" src="~/Scripts/Coordinator.js" ></script>
<script type="text/javascript" src="~/Scripts/MessageBuilder.js" ></script>
<script type="text/javascript" src="~/Scripts/jstz-1.0.4.min.js"></script>

<script type="text/javascript" src="~/Scripts/jquery.tagsinput.js"></script>
@Styles.Render("~/Content/jquery.tagsinput.css")
@Styles.Render("~/Content/Homegrown.css")
@Styles.Render("~/Content/timepicker.css")
<script type="text/javascript">
    $(document).ready(function () {

        $('input[name="StartTime"]').datetimepicker({dateFormat: 'dd/mm/yy'});
        $('input[name="SendAllBy"]').datetimepicker({dateFormat: 'dd/mm/yy'});

        $('#StartTime,#SendAllBy').bind('change keyup blur focus', function () {
            CheckIfMessagesWillBeSentOvernight();
        });
        
        $('#Message').bind('keyup', function () {   
            CountMessageChar($('#SmsContent'));
        });
        CountMessageChar($('#SmsContent'));

        $('#Tags').tagsInput({ autocomplete_url: "/Tag/Search/" });

        $('#UserTimeZone').val(jstz.determine().name());
    });
</script>


<h2>Create Coordinated Messages</h2>

@using (Html.BeginForm("Create", "SmsAndEmail", FormMethod.Post, new Dictionary<string, object>() {{ "enctype", "multipart/form-data"}, {"class", "form-horizontal" }}))
{
    @Html.ValidationSummary(true)

<div>
<h2>Select template or setup your own content... (add more here)</h2>
@Html.DropDownListFor(model => model.TemplateName, ViewData["CommunicationTemplates"] as List<SelectListItem>)
</div>

    <fieldset>
        <div class="control-group">
            @Html.LabelFor(model => model.Topic)
            @Html.EditorFor(model => model.Topic)
            @Html.ValidationMessageFor(model => model.Topic)
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.SmsContent)
            @{ 
                var messageValidationClass = Model != null && !string.IsNullOrWhiteSpace(Model.SmsContent) && Model.SmsContent.Length <= 160 ? "messageInputValid" : "messageInputInvalid";
                messageValidationClass = messageValidationClass + ", span6";
            }
            @Html.TextAreaFor(model => model.SmsContent, new Dictionary<string, object> { { "class", @messageValidationClass } })
            @Html.ValidationMessageFor(model => model.SmsContent)
            <div id="messageCounter"></div>
        </div>
        
        <div class="control-group">
            @Html.LabelFor(model => model.EmailHtmlContent)
            @Html.TextAreaFor(model => model.EmailHtmlContent)
            @Html.ValidationMessageFor(model => model.EmailHtmlContent)
        </div>
        
        <div class="control-group">
            <input type="file" name="FileUpload"/>
        </div>

    </fieldset>
    
    <fieldset id="Timing">
        <div class="control-group">
            @Html.LabelFor(model => model.StartTime, "Start Time")
            @Html.EditorFor(model => model.StartTime)
            @Html.ValidationMessageFor(model => model.StartTime)
            @Html.HiddenFor(model => model.UserTimeZone)
            @Html.ValidationMessageFor(model => model.UserTimeZone)
            @Html.ValidationMessageFor(model => model.SendAllBy)
        </div>
        
        <div id="CoordinationTiming">
            <div id="OvernightWarning" class="warning blockHidden">
                Warning - this will result in messages being sent overnight for your local timezone!
            </div>    
            <div id="SendAllByDiv" class="control-group">
                @Html.LabelFor(model => model.SendAllBy, "End Time")
                @Html.EditorFor(model => model.SendAllBy)
            </div>
        </div>
    </fieldset>

    <fieldset>
        <div class="control-group">
            @Html.LabelFor(model => model.ConfirmationEmail, "Confirmation Email")
            @Html.EditorFor(model => model.ConfirmationEmail)
            @Html.ValidationMessageFor(model => model.ConfirmationEmail)
        </div>
        
        <div class="control-group">
            @Html.LabelFor(model => model.Tags)
            @Html.EditorFor(model => model.Tags)
            @Html.ValidationMessageFor(model => model.Tags)
        </div>

    </fieldset>
    <p>
        <input type="submit" value="Create" />
    </p>
}

SmsScheduler/SmsWeb/Views/SmsAndEmail/CreateSmsAndEmailPickRows.cshtml
@model SmsWeb.Models.DataColumnPicker 

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Styles.Render("~/Content/themes/base/jquery-ui.css")

<!DOCTYPE html>

<html>
    <head>
        <title>Pick your columns</title>
    </head>
    <body>
        <div>
            @using (Html.BeginForm("CreateSmsAndEmailColumnPicker", "SmsAndEmail", FormMethod.Post))
            {
                <h3>Tell us which columns of your spreadsheet to use</h3>
                <div>
                    @Html.LabelFor(m => m.FirstRowIsHeader, "My first row is a header")
                    @Html.CheckBoxFor(m => m.FirstRowIsHeader)
                </div>
                <div>
                    @Html.LabelFor(m => m.CustomerIdColumn, "Customer Id")
                    @Html.DropDownListFor(m => m.CustomerIdColumn, ViewData["selectListData"] as IEnumerable<SelectListItem>)
                </div>
                <div>
                    @Html.LabelFor(m => m.CustomerNameColumn, "Customer Name")
                    @Html.DropDownListFor(m => m.CustomerNameColumn, ViewData["selectListData"] as IEnumerable<SelectListItem>)
                </div>
                <div>
                    @Html.LabelFor(m => m.PhoneNumberColumn, "Mobile Number")
                    @Html.DropDownListFor(m => m.PhoneNumberColumn, ViewData["selectListData"] as IEnumerable<SelectListItem>)
                </div>
                <div>
                    @Html.LabelFor(m => m.EmailColumn, "Email")
                    @Html.DropDownListFor(m => m.EmailColumn, ViewData["selectListData"] as IEnumerable<SelectListItem>)
                </div>
            <input type="submit"/>
            }
        </div>
    </body>
</html>

SmsScheduler/SmsWeb/Views/SmsAndEmail/Details.cshtml
@using SmsTrackingModels
@model SmsWeb.Models.CoordinatorOverview

@{
    ViewBag.Title = "SMS And Email Scheduling : " + Model.Topic;
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

@Styles.Render("~/Content/themes/base/jquery-ui.css")
<script type="text/javascript" src="~/Scripts/jquery-ui-timepicker-addon.js" ></script>
<script type="text/javascript" src="~/Scripts/jstz-1.0.4.min.js"></script>
<script type="text/javascript" src="~/Scripts/tinysort-1.5.2.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

<script type="text/javascript">
    function setupProgressBar(sentMessages, failedMessages, scheduledMessages, pausedMessages, waitingforSchedulingMessages, cancelledMessages) { 
        updateProgressBarSection(totalMessages, cancelledMessages, "progress_cancelled");
        updateProgressBarSection(totalMessages, waitingforSchedulingMessages, "progress_waiting");
        updateProgressBarSection(totalMessages, pausedMessages, "progress_paused");
        updateProgressBarSection(totalMessages, failedMessages, "progress_failed");
        updateProgressBarSection(totalMessages, sentMessages, "progress_success");
        updateProgressBarSection(totalMessages, scheduledMessages, "progress_scheduled");
    };

    function updateProgressBarSection(totalMessageCount, sectionMessageCount, divId) {
        var sectionPercentage = sectionMessageCount / totalMessages * 100;
        $('#' + divId).width(sectionPercentage + "%");
        $('#' + divId).text(sectionMessageCount);
    }

    $(function () {
        window.totalMessages = '@Model.MessageCount';
        window.coordinatorId = '@Model.CoordinatorId';
        var sentMessages = '@Model.MessageStatusCounter.SentCount';
        var failedMessages = '@Model.MessageStatusCounter.FailedCount';
        var scheduledMessages = '@Model.MessageStatusCounter.ScheduledCount';
        var pausedMessages = '@Model.MessageStatusCounter.PausedCount';
        var waitingForSchedulingMessages = '@Model.MessageStatusCounter.WaitingForSchedulingCount';
        var cancelledMessages = '@Model.MessageStatusCounter.CancelledCount';
        setupProgressBar(sentMessages, failedMessages, scheduledMessages, pausedMessages, waitingForSchedulingMessages, cancelledMessages);

        $('input[name="timeToResume"]').datetimepicker({ dateFormat: 'dd/mm/yy' });
        $('input[name="finishTime"]').datetimepicker({ dateFormat: 'dd/mm/yy' });
        $('#UserTimeZone').val(jstz.determine().name());

        var schedule = $.connection.scheduleStatus;

        schedule.client.messageStatusUpdated = function (coordinatorId, sentCount, failedCount, scheduledCount, pausedCount, waitingForSchedulingCount, cancelledCount) {
            if (coordinatorId == window.coordinatorId){
                setupProgressBar(sentCount, failedCount, scheduledCount, pausedCount, waitingForSchedulingCount, cancelledCount);
            }
        };
        
        schedule.client.coordinatorCompleted = function (message) {
            var coordinatorSummary = "<div>Current Status: Complete</div>" +
                "<div>Completion Date: " + message.CompletedAt + "</div>";
            $('#' + message.CoordinatorId).html(coordinatorSummary);
        };
        
        // Start the connection
        $.connection.hub.start();

        $("#pauseForm").submit(function () {
            return confirm("Are you sure you want to pause the current coordinator?");
        });
    });

</script>

<h2>SMS And Email Scheduling</h2>
<div>ID : @Model.CoordinatorId</div>


<div id="@Model.CoordinatorId">
    <div class="control-group">Current Status: @Model.CurrentStatus.ToString()</div>
    @if (Model.CurrentStatus != CoordinatorStatusTracking.Completed)
    {
        if (Model.CurrentStatus == CoordinatorStatusTracking.Started)
        {
            <div>
                @using(Html.BeginForm("Pause", "Coordinator", FormMethod.Post, new { id = "pauseForm" }))
                {
                    @Html.HiddenFor(m => m.CoordinatorId)
                    @*<input type="submit" value="Pause Message Sending"/>*@
                }
            </div>
        }
        if (Model.CurrentStatus == CoordinatorStatusTracking.Paused)
        {
            <div>
                @using(Html.BeginForm("Resume", "Coordinator", FormMethod.Post, new { id = "resumeForm" }))
                {
                    @Html.HiddenFor(m => m.CoordinatorId)
                    <div class="control-group">
                        <label>Time to resume</label>
                        @Html.Editor("timeToResume")
                        @Html.ValidationMessage("timeToResume")
                    </div>
                    
                    <div class="control-group">
                        <label>Finish Time (optional)</label>
                        @Html.Editor("finishTime")
                        @Html.ValidationMessage("finishTime")
                        <div><sup>This will update the timing of messages instead of just updating the schedule.</sup></div>
                    </div>
                    @Html.Hidden("UserTimeZone");
                    
                    @*<input type="submit" value="Resume Messages"/>*@
                }
            </div>
        }
    }
    @if(Model.CompletionDateUtc.HasValue)
    {
        <div>Completion Date: @Model.CompletionDateUtc.Value.ToLocalTime()</div>

    }
</div>

<table class="table">
    <tr>
        <th>Number of Messages</th>
        <td>@Model.MessageCount</td>
    </tr>
    <tr>
        <th>Message Body</th>
        <td>@Model.MessageBody</td>
    </tr>
    @if (Model.CurrentStatus == CoordinatorStatusTracking.Started)
    {
        if (Model.NextScheduledMessageDate != null)
        {
            <tr>
                <th>Next Scheduled Message (UTC)</th>
                <td>
                    @if (Model.NextScheduledMessageDate == null){
                        @:"Waiting for scheduling"
                    } else {
                        @Model.NextScheduledMessageDate
                    }
                </td>
            </tr>
        }
        if (Model.FinalScheduledMessageDate != null)
         {
             <tr>
                 <th>Final Scheduled Message (UTC)</th>
                 <td>
                     @if (Model.FinalScheduledMessageDate == null)
                     {
                        @:"Waiting for scheduling"
                     } else {
                        @Model.FinalScheduledMessageDate  
                     }
                 </td>
             </tr>
         }
    }
</table>
@*<div class="progress active" style="max-width: 100%;">*@
@*    <div class="bar bar-info" id="progress_waiting" title="Waiting to be scheduled"></div>*@
@*    <div class="bar bar-info" id="progress_scheduled" title="Scheduled to be sent"></div>*@
@*    <div class="bar bar-info" id="progress_paused" title="Paused"></div>*@
@*    <div class="bar bar-success" id="progress_success" title="Delivered!"></div>*@
@*    <div class="bar bar-danger" id="progress_failed" title="Delivery failed"></div>*@
@*    <div class="bar bar-danger" id="progress_cancelled" title="Cancelled"></div>*@
@*</div>*@

@if (Model.CoordinatorSummary.Count(c => c.Type == ScheduleType.Sms) > 0)
{
    <div>
        <h3>SMS</h3>
        <p>@Model.SmsBody</p>
        <table class="table minwidth-table">
            <thead><tr><th>Status</th><th>Count</th><th>Cost</th></tr></thead>
            <tbody>
                @foreach (var summary in Model.CoordinatorSummary.Where(c => c.Type == ScheduleType.Sms))
                {
                    <tr><td>@summary.Status</td><td>@summary.Count</td><td>@summary.Cost</td></tr>
                }
            </tbody>
        </table>
    </div>
}
@if (Model.CoordinatorSummary.Count(c => c.Type == ScheduleType.Email) > 0)
{
    <div>
        <h3>Email</h3>
        <p>@Model.EmailBody</p>
        <table class="table minwidth-table">
            <thead><tr><th>Status</th><th>Count</th></tr></thead>
            <tbody>
                @foreach (var summary in Model.CoordinatorSummary.Where(c => c.Type == ScheduleType.Email))
                {
                    <tr><td>@summary.Status</td><td>@summary.Count</td></tr>
                }
            </tbody>
        </table>
    </div>
}