SmsScheduler/SmsWeb/Models/Contact.cs
namespace SmsWeb.Models
{
    public class Contact
    {
        public string Name { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
    }
}

SmsScheduler/SmsWeb/Controllers/DefaultEmailController.cs
using System.Linq;
using System.Web.Mvc;
using ConfigurationModels;
using ServiceStack.Common;
using SmsWeb.Models;

namespace SmsWeb.Controllers
{
    public class DefaultEmailController : Controller
    {
        public IRavenDocStore DocumentStore { get; set; }

        public PartialViewResult DetailsAjax()
        {
            using (var session = DocumentStore.GetStore().OpenSession("Configuration"))
            {
                var emailDefaultNotification = session.Load<EmailDefaultNotification>("EmailDefaultConfig");
                var defaultEmailModel = new DefaultEmailModel();
                if (emailDefaultNotification == null || emailDefaultNotification.EmailAddresses.Count == 0)
                    return PartialView("_DefaultEmailConfigEdit", defaultEmailModel);
                var defaultEmails = emailDefaultNotification.EmailAddresses.Join(", ");
                defaultEmailModel.DefaultEmails = defaultEmails;
                return PartialView("_DefaultEmailConfigDetails", defaultEmailModel);
            }
        }

        public PartialViewResult EditAjax()
        {
            using (var session = DocumentStore.GetStore().OpenSession("Configuration"))
            {
                var emailDefaultNotification = session.Load<EmailDefaultNotification>("EmailDefaultConfig");
                var defaultEmailModel = new DefaultEmailModel();
                if (emailDefaultNotification == null || emailDefaultNotification.EmailAddresses.Count == 0)
                    return PartialView("_DefaultEmailConfigEdit", defaultEmailModel);
                var defaultEmails = emailDefaultNotification.EmailAddresses.Join(", ");
                defaultEmailModel.DefaultEmails = defaultEmails;
                return PartialView("_DefaultEmailConfigEdit", defaultEmailModel);
            }
        }

        [HttpPost]
        public PartialViewResult EditAjax(DefaultEmailModel configuration)
        {
            var isValid = TryUpdateModel(configuration);
            if (!isValid)
                return PartialView("_DefaultEmailConfigEdit", configuration);
            using (var session = DocumentStore.GetStore().OpenSession("Configuration"))
            {
                var emailAddresses = configuration.DefaultEmails.Split(',');
                var cleanedEmailInList = emailAddresses.ToList().Select(e => e.Trim()).ToList();
                var emailDefaultNotification = session.Load<EmailDefaultNotification>("EmailDefaultConfig");
                if (emailDefaultNotification == null)
                {
                    var defaultNotification = new EmailDefaultNotification { EmailAddresses = cleanedEmailInList };
                    session.Store(defaultNotification, "EmailDefaultConfig");
                }
                else
                {
                    emailDefaultNotification.EmailAddresses = cleanedEmailInList;
                }
                session.SaveChanges();
                return PartialView("_DefaultEmailConfigDetails", configuration);
            }
        }
    }
}

SmsScheduler/SmsWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using ConfigurationModels;
using Raven.Client.Linq;
using SmsTrackingModels;
using System.Linq;
using SmsTrackingModels.RavenIndexs;
using SmsWeb.Models;

namespace SmsWeb.Controllers
{
    public class HomeController : Controller
    {
        public IRavenDocStore RavenDocStore { get; set; }

        public ActionResult Index()
        {
            using (var session = RavenDocStore.GetStore().OpenSession("Configuration"))
            {
                var twilioConfiguration = session.Load<TwilioConfiguration>("TwilioConfig");
                var mailgunConfiguration = session.Load<MailgunConfiguration>("MailgunConfig");

                if (twilioConfiguration == null || mailgunConfiguration == null)
                    return View("IndexConfigNotSet");
                else
                    return RedirectToAction("Create", "Coordinator");
            }
            return View("Index");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Configuration()
        {
            return View("ConfigMenu");
        }

        [HttpPost]
        public ActionResult Search(string id)
        {
            Guid docId;

            if (Guid.TryParse(id, out docId))
            {
                using (var session = RavenDocStore.GetStore().OpenSession())
                {
                    var trackingData = session.Load<object>(docId.ToString());
                    if (trackingData != null)
                    {
                        if (trackingData is CoordinatorTrackingData)
                            return RedirectToAction("Details", "Coordinator", new {coordinatorId = id});
                        throw new Exception("Type not recognised");
                    }
                }
            }
            else
            {
                using (var session = RavenDocStore.GetStore().OpenSession())
                {
                    var list = session.Query<SmsActioned.Result, SmsActioned>()
                        .Where(p => p.Number.EndsWith(id))
                        .Select(p => new SearchByNumberResult
                        {
                            PhoneNumber = p.Number,
                            SendingDate = p.ActionTime,
                            Status = p.Status,
                            Topic = p.Topic
                        })
                        .ToList();

                    return View("Results", list);

                    //var reduceResults = session.Query<PhoneNumberInCoordinatedMessages.ReduceResult, PhoneNumberInCoordinatedMessages>()
                    //    .Where(p => p.PhoneNumber.StartsWith(id))
                    //    .Select(p => new SearchByNumberResult
                    //        {
                    //            CoordinatorId = p.CoordinatorId,
                    //            PhoneNumber = p.PhoneNumber,
                    //            SendingDate = p.SendingDate,
                    //            Status = p.Status,
                    //            Topic = p.Topic,

                    //        })
                    //    .ToList();
                    //return View("Results", reduceResults);
                }
            }
            return View("NoResults", (object)id);
        }
    }
}

SmsScheduler/SmsWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

SmsScheduler/SmsWeb/Views/Home/ConfigMenu.cshtml
@{
    ViewBag.Title = "SMS Configuration";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
@Scripts.Render("~/Scripts/jquery.1.8.3.min.js")
<h2>Configuration</h2>

<style>
    .ConfigDiv {
        float: left;
        width: 45%;
        border: 1px dotted #852d5d;
        padding: 10px;
        margin: 10px;
    }

    .Details {
        padding-bottom: 5px;
        margin-bottom: 5px;
    }
</style>

<div>
    <div class="ConfigDiv" id="TwilioConfigDiv">
        @Html.Action("DetailsAjax", "TwilioConfig")
    </div>
    <div class="ConfigDiv" id="MailgunConfigDiv">
        @Html.Action("DetailsAjax", "MailgunConfig")
    </div>
    <div class="ConfigDiv" id="DefaultEmailConfigDiv">
        @Html.Action("DetailsAjax", "DefaultEmail")
    </div>
    <div class="ConfigDiv" id="CountryCodeConfigDiv">
        @Html.Action("DetailsAjax", "CountryCodeConfig")
    </div>
</div>

SmsScheduler/SmsWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "SMS Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Online</h3>
    </header>
    <p>
        <span class="label">Twitter:</span>
        <span><a href="http://twitter.com/sam_jeffress">@@sam_jeffress</a></span>
    </p>
    <p>
        <span class="label">GitHub:</span>
        <span><a href="http://github.com/samjeffress">GitHub</a></span>
    </p>
    <p>
        <span class="label">Blog:</span>
        <span><a href="http://unstructuredthinking.blogspot.com">Unstructured Thinking</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Fork the project</h3>
    </header>
    <p>
        <span class="label">GitHub:</span>
        <span><a href="http://github.com/samjeffress/smscoordinator">Sms Coordinator</a></span>
    </p>
</section>

SmsScheduler/SmsWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "SMS Coordinator";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

<div class="hero-unit">
    <h1>Send That Message!</h1>
    <p>Need to send loads of text messages? We've got you covered.</p>
    <p>Using our coordinator you can send your messages over a set time so you can manage the work generated by your campaign.</p>
    <p>Create your message schedules through our webpage or the api to hook directly into your app.</p>
</div>

SmsScheduler/SmsWeb/Views/Home/IndexConfigNotSet.cshtml
@{
    ViewBag.Title = "SMS Coordinator : Almost There!";
    Layout = "~/Views/Shared/_BootstrapLayout.basic.cshtml";
}

@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
@Scripts.Render("~/Scripts/jquery.1.8.3.min.js")


<div class="hero-unit">
    <h1>Send That Message!</h1>
    <p>Need to send loads of text messages? We've got you covered.</p>
    <p>Using our coordinator you can send your messages over a set time so you can manage the work generated by your campaign.</p>
    <p>Create your message schedules through our webpage or the api to hook directly into your app.</p>
    <p>To get started you'll need to setup a <a href="http://www.twilio.com">Twilio</a> and <a href="http://www.mailgun.com">Mailgun</a> account. We use these to deliver your SMS' and confirmation emails.</p>
    @*<p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>*@
</div>

<div>
    <div style="float: left; width: 50%" id="TwilioConfigDiv">
        @Html.Action("EditAjax", "TwilioConfig")
    </div>
    <div style="float: left; width: 50%" id="MailgunConfigDiv">
        @Html.Action("EditAjax", "MailgunConfig")
    </div>
</div>

SmsScheduler/SmsWeb/Views/Home/NoResults.cshtml
@model string

@{
    ViewBag.Title = "SMS Search Results";
    Layout = "~/Views/shared/_BootstrapLayout.basic.cshtml";
}

<h2>No Results</h2>
<div>Sorry, we couldn't find any results for  '@Model' - please try again with another id.</div>

SmsScheduler/SmsWeb/Views/Home/Results.cshtml
@model IEnumerable<SmsWeb.Models.SearchByNumberResult>

@{
    ViewBag.Title = "SMS Search Results";
    Layout = "~/Views/Shared/_BootstrapLayout.basic.cshtml";
}

<h2>Results</h2>

<table class="table table-bordered table-striped table-hover">
    <thead>
    
        <tr>
            <th>Phone Number</th>
            <th>Sent Date</th>
            <th>Status</th>
            <th>Topic</th>
            <th>CoordinatorId</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.PhoneNumber)</td>
                <td>@Html.DisplayFor(modelItem => item.SendingDate)</td>
                <td>@Html.DisplayFor(modelItem => item.Status)</td>
                <td>@Html.DisplayFor(modelItem => item.Topic)</td>
                <td>@if (item.CoordinatorId != null)
                    {
                        @Html.ActionLink(item.CoordinatorId, "Details", "Coordinator", new {CoordinatorId = item.CoordinatorId}, null)
                    }</td>
            </tr>
        }
    </tbody>


</table>